src/app/models/category.py
from .tool import Tool
from typing import List


class Category:
    def __init__(self, id=None, name=None, path=None):
        """
        初始化 Category 对象。

        参数:
        id (int): 类别的唯一标识符。
        name (str): 类别的名称。
        """
        self._id = id
        self._name = name
        self._path = path
        self._tools: List[Tool] = []

    @property
    def id(self):
        """
        获取类别的唯一标识符。

        返回:
        int: 类别的唯一标识符。
        """
        return self._id

    @id.setter
    def id(self, value):
        """
        设置类别的唯一标识符。

        参数:
        value (int): 新的类别唯一标识符。
        """
        self._id = value

    @property
    def name(self):
        """
        获取类别的名称。

        返回:
        str: 类别的名称。
        """
        return self._name

    @name.setter
    def name(self, value):
        """
        设置类别的名称。

        参数:
        value (str): 新的类别名称。
        """
        self._name = value

    @property
    def path(self):
        """
        获取类别的真实路径。

        返回:
        str: 类别的真实路径。
        """
        return self._path

    @path.setter
    def path(self, value):
        """
        设置类别的真实路径。

        参数:
        value (str): 新的类别真实路径。
        """
        self._path = value
        
    @property
    def tools(self) -> List[Tool]:
        """
        获取类别中的工具列表。

        返回:
        list: 工具对象的列表。
        """
        return self._tools

src/app/models/tool.py
class Tool:
    def __init__(self, id=None, name=None):
        """
        初始化 Tool 对象。

        参数:
        id (int): 工具的唯一标识符。
        name (str): 工具的名称。
        """
        self._id = id
        self._name = name

    @property
    def id(self):
        """
        获取工具的唯一标识符。

        返回:
        int: 工具的唯一标识符。
        """
        return self._id

    @id.setter
    def id(self, value):
        """
        设置工具的唯一标识符。

        参数:
        value (int): 新的工具唯一标识符。
        """
        self._id = value

    @property
    def name(self):
        """
        获取工具的名称。

        返回:
        str: 工具的名称。
        """
        return self._name

    @name.setter
    def name(self, value):
        """
        设置工具的名称。

        参数:
        value (str): 新的工具名称。
        """
        self._name = value

src/app/__init__.py
from flask import Flask, render_template
app = Flask(__name__)

# 捕获其他 HTTP 错误
@app.errorhandler(Exception)
def handle_exception(e):
    return render_template('404.html'), 404

# 导入配置
from config import Config
app.config.from_object(Config)

# 导入蓝图并注册
from app.views import toolbox
app.register_blueprint(toolbox.bp)

src/app/views/toolbox.py
from flask import Blueprint, render_template, request
from config import Config
from flask import redirect

bp = Blueprint("toolbox", __name__)


@bp.route("/")
@bp.route("/toolbox")
@bp.route("/toolbox/<string:category_id>")
@bp.route("/toolbox/<string:category_id>/<string:tool_id>")
def tool_page(category_id=None, tool_id=None):
    if not category_id:
        category_id = Config.TOOLS[0].id
        tool_id = Config.TOOLS[0].tools[0].id
        # 304 redirect
        return redirect(f"/toolbox/{category_id}/{tool_id}")
    category = next((cat for cat in Config.TOOLS if cat.id == category_id), None)
    if category:
        if not tool_id:
            tool_id = category.tools[0].id
            return redirect(f"/toolbox/{category_id}/{tool_id}")
        for tool in category.tools:
            if tool.id == tool_id:
                return render_template(
                    "tool_page.html",
                    category=category,
                    tool=tool,
                    categories=Config.TOOLS,
                    tools=category.tools,
                )
    else:
        return "Category not found", 404


@bp.route("/toolbox/content")
def tool_page_content():
    category_id = request.args.get("category_id")
    category = next((cat for cat in Config.TOOLS if cat.id == category_id), None)
    if not category:
        return "Category not found", 404
    tool_id = request.args.get("tool_id")
    if not tool_id or tool_id == "undefined":
        tool_id = category.tools[0].id
    # 渲染工具内容
    return render_template(f"tools/{category.path}/{tool_id}")

@bp.route("/toolbox/navbar-content")
def navbar_content():
    category_id = request.args.get("category_id")
    category = next((cat for cat in Config.TOOLS if cat.id == category_id), None)
    if not category:
        return "Category not found", 404
    # 渲染navbar内容
    return render_template(f"navbar.html", tools = category.tools, category = category)

src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='css/output.css') }}" rel="stylesheet">
    <title>{% block title %}Magic Box{% endblock %}</title>
    <style>
        @font-face {
            font-family: 'Source Han Sans Simplified C';
            src: url("{{ url_for('static', filename='font/Source-Han-Sans-CN-Regular.woff') }}") format('woff');
            font-weight: normal;
            font-style: normal;
        }

        body {
            font-family: 'Source Han Sans Simplified C', sans-serif;
        }
    </style>
</head>

<body class="bg-gray-100">
    <div class="container mx-auto p-4">
        <h1 class="text-3xl font-bold mb-6 text-center text-blue-600">Magic Box</h1>
        <div class="flex bg-white shadow-lg rounded-lg overflow-hidden">
            <!-- 左侧分类导航栏 -->
            <div class="w-1/8 border-r">
                <nav class="flex flex-col">
                    {% block nav %}
                    {% endblock %}
                </nav>
            </div>
            <!-- 右侧工具内容 -->
            <div class="w-7/8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

src/app/templates/nav.html
{% extends "base.html" %}

{% block nav %}
{% for category in categories %}
<button class="py-4 px-6 text-left border-b hover:bg-blue-100 focus:outline-none transition duration-300"
    onclick="loadNavBarContent('{{ category.id }}')">{{ category.name }}</button>
{% endfor %}
{% endblock %}

src/app/templates/navbar.html
<nav class="flex flex-row">
    <div class="inline-flex">
        {% for tool in tools %}
        <!-- <a href="{{ url_for('toolbox.tool_page', category_id=category.id, tool_id=tool.id) }}"> -->
        <button
            class="py-4 px-6 text-center border-r hover:bg-blue-100 focus:outline-none transition duration-300"
            onclick="loadToolContent('{{ category.id }}', '{{ tool.id }}')">
            {{ tool.name }}</button>
        {% endfor %}
        <!-- </a> -->
    </div>
</nav>

src/app/templates/tool_page.html
{% extends "nav.html" %}

{% block title %}Magic Box - {{ category.name }}{% endblock %}

{% block content %}
<div class="pl-3">
    <div id="navbar" class="border-b">
        {% include 'navbar.html' %}
    </div>

    <div id="tool-content">
        {% include 'tools/' + category.path + '/' + tool.id %}
    </div>
</div>
<script>
    function loadNavBarContent(categoryId) {
        const currentUrl = new URL(window.location.href);
        const currentCategoryId = currentUrl.pathname.split('/')[2];
        if (currentCategoryId !== categoryId) {
            const url = new URL('{{ url_for("toolbox.navbar_content") }}', window.location.origin);
            url.searchParams.append('category_id', categoryId);
            fetch(url)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.text();
                })
                .then(html => {
                    document.getElementById('navbar').innerHTML = html;
                })
                .catch(error => {
                    console.error('Error loading narbar content:', error);
                });
        }
        loadToolContent(categoryId)
    }

    function loadToolContent(categoryId, toolId, nopush = false) {
        // Get current URL parameters
        const currentUrl = new URL(window.location.href);
        const currentCategoryId = currentUrl.pathname.split('/')[2];
        const currentToolId = currentUrl.pathname.split('/')[3];

        // Check if the new state is the same as the current state
        if (currentCategoryId === categoryId && currentToolId === toolId) {
            nopush = true;
        }

        const url = new URL('{{ url_for("toolbox.tool_page_content") }}', window.location.origin);
        url.searchParams.append('category_id', categoryId);
        if (toolId) {
            url.searchParams.append('tool_id', toolId);
        }

        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.text();
            })
            .then(html => {
                document.getElementById('tool-content').innerHTML = html;
                // Update the URL without reloading the page
                let newUrl = `/toolbox/${categoryId}`;
                if (toolId) {
                    newUrl += `/${toolId}`;
                    if (!nopush) {
                        history.pushState({ categoryId, toolId }, '', newUrl);
                    }
                }
                else {
                    if (!nopush) {
                        history.pushState({ categoryId }, '', newUrl);
                    }
                }

            })
            .catch(error => {
                console.error('Error loading tool content:', error);
            });
    }

    // Handle back/forward navigation
    window.addEventListener('popstate', function (event) {
        if (event.state) {
            console.log('popstate:', event.state);
            loadToolContent(event.state.categoryId, event.state.toolId, true);
        }
    });
</script>
{% endblock %}

src/app/templates/toolbox.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static', filename='css/output.css') }}" rel="stylesheet">
    <title>farm</title>
    <style>
        @font-face {
            font-family: 'Source Han Sans Simplified C';
            src: url("{{ url_for('static', filename='font/Source-Han-Sans-CN-Regular.woff') }}") format('woff');
            font-weight: normal;
            font-style: normal;
        }

        body {
            font-family: 'Source Han Sans Simplified C', sans-serif;
        }
    </style>
</head>

<body class="bg-gray-100">
    <div class="container mx-auto p-4">
        <h1 class="text-3xl font-bold mb-6 text-center text-blue-600">Magic Box</h1>
        <div class="flex bg-white shadow-lg rounded-lg overflow-hidden">
            <!-- 左侧分类导航栏 -->
            <div class="w-1/8 border-r">
                <nav class="flex flex-col">
                    <button
                        class="py-4 px-6 text-left border-b hover:bg-blue-100 focus:outline-none transition duration-300"
                        onclick="showCategory('devTools')">开发工具</button>
                    <button
                        class="py-4 px-6 text-left border-b hover:bg-blue-100 focus:outline-none transition duration-300"
                        onclick="showCategory('codecTools')">编解码</button>
                    <button class="py-4 px-6 text-left hover:bg-blue-100 focus:outline-none transition duration-300"
                        onclick="showCategory('bizTools')">业务工具</button>
                </nav>
            </div>
            <!-- 右侧工具内容 -->
            <div class="w-7/8">
                <!-- 开发工具 -->
                <div id="devTools" class="pl-3">
                    <div class="border-b mb-4">
                        <nav class="flex">
                            <div class="inline-flex">
                                <button
                                    class="py-4 px-6 text-center border-r hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool-timestamp')">时间戳</button>
                                <button
                                    class="py-4 px-6 text-center hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool-jwt')">JWT</button>
                            </div>
                        </nav>
                    </div>
                    {% include 'tools/timestamp.html' %}
                    {% include 'tools/jwt.html' %}
                </div>
                <!-- 编解码工具 -->
                <div id="codecTools" class="pl-3 hidden">
                    <div class="border-b mb-4">
                        <nav class="flex">
                            <div class="inline-flex">
                                <button
                                    class="py-4 px-6 text-center border-r hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool4')">工具4</button>
                                <button
                                    class="py-4 px-6 text-center border-r hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool5')">工具5</button>
                                <button
                                    class="py-4 px-6 text-center hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool6')">工具6</button>
                            </div>
                        </nav>
                    </div>
                    <div id="tool4" class="p-6">
                        <h2 class="text-2xl font-semibold mb-4 text-blue-600">工具4</h2>
                        <p class="text-gray-700">这里是工具4的内容。</p>
                    </div>
                    <div id="tool5" class="p-6 hidden">
                        <h2 class="text-2xl font-semibold mb-4 text-blue-600">工具5</h2>
                        <p class="text-gray-700">这里是工具5的内容。</p>
                    </div>
                    <div id="tool6" class="p-6 hidden">
                        <h2 class="text-2xl font-semibold mb-4 text-blue-600">工具6</h2>
                        <p class="text-gray-700">这里是工具6的内容。</p>
                    </div>
                </div>
                <!-- 业务工具 -->
                <div id="bizTools" class="pl-3 hidden">
                    <div class="border-b mb-4">
                        <nav class="flex">
                            <div class="inline-flex">
                                <button
                                    class="py-4 px-6 text-center border-r hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool7')">工具7</button>
                                <button
                                    class="py-4 px-6 text-center border-r hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool8')">工具8</button>
                                <button
                                    class="py-4 px-6 text-center hover:bg-blue-100 focus:outline-none transition duration-300"
                                    onclick="showTool('tool9')">工具9</button>
                            </div>
                        </nav>
                    </div>
                    <div id="tool7" class="p-6">
                        <h2 class="text-2xl font-semibold mb-4 text-blue-600">工具7</h2>
                        <p class="text-gray-700">这里是工具7的内容。</p>
                    </div>
                    <div id="tool8" class="p-6 hidden">
                        <h2 class="text-2xl font-semibold mb-4 text-blue-600">工具8</h2>
                        <p class="text-gray-700">这里是工具8的内容。</p>
                    </div>
                    <div id="tool9" class="p-6 hidden">
                        <h2 class="text-2xl font-semibold mb-4 text-blue-600">工具9</h2>
                        <p class="text-gray-700">这里是工具9的内容。</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function showCategory(categoryId) {
            document.getElementById('devTools').classList.add('hidden');
            document.getElementById('codecTools').classList.add('hidden');
            document.getElementById('bizTools').classList.add('hidden');
            document.getElementById(categoryId).classList.remove('hidden');
        }

        function showTool(toolId) {
            const tools = document.querySelectorAll('[id^="tool"]');
            tools.forEach(tool => tool.classList.add('hidden'));
            document.getElementById(toolId).classList.remove('hidden');
        }
    </script>
</body>

</html>

src/app/templates/tools/001_dev/jwt.html
<div id="tool-jwt" class="p-6 hidden">
    <h2 class="text-2xl font-semibold mb-4 text-blue-600">JWT</h2>
    <p class="text-gray-700">这里是工具2的内容。</p>
</div>

src/app/templates/tools/001_dev/timestamp.html
<div id="tool-timestamp" class="p-6 pt-3">
    <h2 class="text-2xl font-semibold mb-4 text-blue-600">时间戳工具</h2>
    <!-- 时间戳工具 -->
    <div class="mb-4">
        <label for="timestamp" class="block text-gray-700">时间戳:</label>
        <input type="text" id="timestamp" class="border rounded p-2 w-full" placeholder="输入时间戳" onkeydown="if(event.key === 'Enter') convertToBeijingTime()">
        <button onclick="convertToBeijingTime()" class="mt-2 bg-blue-500 text-white py-2 px-4 rounded-full">转换为北京时间</button>
    </div>
    <div class="mb-4">
        <label for="beijingTime" class="block text-gray-700">北京时间:</label>
        <input type="text" id="beijingTime" class="border rounded p-2 w-full" placeholder="输入北京时间 (YYYY-MM-DD HH:MM:SS)" onkeydown="if(event.key === 'Enter') convertToTimestamp()">
        <button onclick="convertToTimestamp()" class="mt-2 bg-blue-500 text-white py-2 px-4 rounded-full">转换为时间戳</button>
    </div>
    <div id="result" class="mt-4 text-gray-700" onclick="copyToClipboard(event)" style="cursor: pointer;"></div>
    <div id="copy-feedback" class="hidden text-green-500 mt-2">✔ 复制成功</div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // 显示当前时间戳（毫秒级）
        const currentTimestamp = Date.now();
        document.getElementById('result').innerText = `当前时间戳: ${currentTimestamp}`;
    });

    function convertToBeijingTime() {
        const timestampInput = document.getElementById('timestamp').value;
        const timestamp = parseInt(timestampInput, 10);
        if (isNaN(timestamp)) {
            document.getElementById('result').innerText = '请输入有效的时间戳';
            return;
        }
        const date = new Date(timestamp);
        const beijingTime = date.toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' });
        document.getElementById('result').innerText = `北京时间: ${beijingTime}`;
    }

    function convertToTimestamp() {
        const beijingTimeInput = document.getElementById('beijingTime').value;
        const date = new Date(beijingTimeInput.replace(/-/g, '/'));
        if (isNaN(date.getTime())) {
            document.getElementById('result').innerText = '请输入有效的北京时间';
            return;
        }
        const timestamp = date.getTime();
        document.getElementById('result').innerText = `时间戳: ${timestamp}`;
    }

    function copyToClipboard(event) {
        const text = event.target.innerText;
        navigator.clipboard.writeText(text).then(() => {
            const feedback = document.getElementById('copy-feedback');
            feedback.classList.remove('hidden');
            setTimeout(() => {
                feedback.classList.add('hidden');
            }, 2000);
        }).catch(err => {
            console.error('复制失败: ', err);
        });
    }
</script>

src/app/templates/tools/002_en_decode/base64.html
<div id="tool-jwt" class="p-6 hidden">
    <h2 class="text-2xl font-semibold mb-4 text-blue-600">JWT</h2>
    <p class="text-gray-700">这里是工具2的内容。</p>
</div>

src/app/templates/tools/003_biz/jwt.html
<div id="tool-jwt" class="p-6 hidden">
    <h2 class="text-2xl font-semibold mb-4 text-blue-600">JWT</h2>
    <p class="text-gray-700">这里是工具2的内容。</p>
</div>